### ISSUE TITLE
Update README for ASSEMBLY Language

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#100]
Go to the folder for **Assembly** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to create a README for the same and make sure it covers all instructions on how to set up Assembly Environment.

The README should also contain steps to install that language on various OSs like Mac, Linux and Windows. If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by divayprakash** [comment]
@salman-bhai Working on it!
