### ISSUE TITLE
C# - Add Instructions for compiling in Linux and Mac systems

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#101]
Go to the folder for **C#** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up C# Dev Environment. For more resources, you can check them out [here](https://askubuntu.com/questions/233626/can-i-write-programs-in-c-on-ubuntu)

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by Duxy1996** [comment]
Hey, it is my first time dooing this stuff. Can I do this task? I have programmed in C# a lot but I have never contribuited in one repo.
Thanks 4 all, and greate git.

**Comment by sbshah97** [comment]
Sure why not!

**Comment by sbshah97** [comment]
Sure why not!

**Comment by sbshah97** [comment]
Any updates? 6 Hours more and then the Issue will be re-assigned!

**Comment by Duxy1996** [comment]
yes, Im working on it, this afternoon I will upload the readme

**Comment by sbshah97** [comment]
@Duxy1996 claim the Issue again in case you're still working on it!
