### ISSUE TITLE
Dart - Edit README to add Windows and MacOS

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#103]
Go to the folder for **Dart** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up Dart Dev Environment and how to run the code on Windows and MacOS.

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by manmadeofmayo** [comment]
I'd like to claim this. By 'first-timers-only', do you mean first time for hacktoberfest, or first time with the language?

**Comment by sbshah97** [comment]
I mean `first-timers for Hacktoberfest`

**Comment by sbshah97** [comment]
Please re claim the Issue in case you are sending a PR!

**Comment by grrttedwards** [comment]
Hello again :)

I will claim this if the user above is away.

**Comment by sbshah97** [comment]
Issue assigned to @grrttedwards
