### ISSUE TITLE
Erlang - Add Windows and MacOS Documentation

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#104]
Go to the folder for **Erlang** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up Erlang Dev Environment on Windows and MacOS and try to send a Pull Request with the same! 

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by jbmiles** [comment]
Hey!

I have no experience with open source projects, and this looks like a reasonably simple place to start.
I'd love to take it on!

**Comment by sbshah97** [comment]
Sure go ahead!

**Comment by sbshah97** [comment]
Issue assigned to @jbmiles
