### ISSUE TITLE
F# - Add README for Linux and MacOS

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#106]
Go to the folder for **F#** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up F# Dev Environment in Linux and MacOS.

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by helloimkat** [comment]
It's my first time doing hacktoberfest, so excuse me - how do we claim thing? Would like to do this, if it's still open.

**Comment by sbshah97** [comment]
Issue assigned to @helloimkat

**Comment by igorpadovan** [comment]
If @helloimkat dind'n do it, assigne to me.

**Comment by helloimkat** [comment]
@igorpadovan working on it ;)

**Comment by sbshah97** [comment]
@igorpadovan 24 hours man! Patience! Lots of other Issues as well on this repo!
