### ISSUE TITLE
Fortran 90 - Add README for MacOS and Windows 

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#107]
Go to the folder for **Fortran 90** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up Fortran 90 Dev Environment in Windows and MacOS.
 
If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by eosti** [comment]
I'd like to claim this one. Before I send the pull request, can you explain how to reference an issue in a pull request? Thank you!

**Comment by eosti** [comment]
Well I goofed the first one and didn't squash the commits, but the second one should be fine. I closed the first one due to it not meeting the rules.

**Comment by sbshah97** [comment]
Alright not an Issue!
