### ISSUE TITLE
Julia - Edit README for adding instructions to run Julia in Windows and MacOS

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#108]
Go to the folder for **Julia** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up Julia Dev Environment for Windows and MacOS. 

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by harsha7890** [comment]
can you send me the steps of installation

**Comment by sbshah97** [comment]
@harsha7890 you'll have to google them out and set up on your local system! That's the whole point of this repository. So that people get to learn new technologies, frameworks and languages! 
:stuck_out_tongue: Would you like to claim the Issue!

**Comment by bege13mot** [comment]
I would like to work on this issue if @harsha7890 doesn't mind.

**Comment by sbshah97** [comment]
@bege13mot Ideally it's preferred one person works on one Issue wrt Documentation Issues!

**Comment by bege13mot** [comment]
ok. leave it

**Comment by sbshah97** [comment]
For now Issue assigned to @harsha7890 !

**Comment by sbshah97** [comment]
Issue will be re-assigned in 16 hours from now!

**Comment by sbshah97** [comment]
ANy updates @harsha7890

**Comment by ivanzaqqa** [comment]
Please i want to contribute in this issue @salman-bhai , i've already git clone this

**Comment by sbshah97** [comment]
Issue assigned to @ivanzaqqa

**Comment by sbshah97** [comment]
Any updates @ivanzaqqa

**Comment by sbshah97** [comment]
Any updates, @ivanzaqqa ?

**Comment by Nythiennzo** [comment]
Please have look at #188 
It's my first time commenting on an issue.
