### ISSUE TITLE
PHP - Add Instructions to install and run PHP in Linux and MacOS

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#111]
Go to the folder for **PHP** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up PHP Dev Environment on Linux and MacOS and how to run the same as well. 

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by shubhammatta** [comment]
I would like to work on this. (as a first-timer)

**Comment by sbshah97** [comment]
Go ahead! Issue assigned to @shubhammatta

**Comment by sbshah97** [comment]
Any updates here?

**Comment by shubhammatta** [comment]
Made changes to PR, Can you check.
