### ISSUE TITLE
Piet - Add Installation instructions for Piet on Windows, Linux and MacOS

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#112]
Go to the folder for **Piet** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up Piet Dev Environment on Windows, Linux and MacOS and how to run the same as well. 

- [ ] Windows
- [ ] Linux
- [ ] Mac

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by bege13mot** [comment]
Hello, I would like to work on this.

**Comment by sbshah97** [comment]
@bege13mot Issue assigned to you! Make sure when you send a PR you do the following as well! 
```
Hi, kindly reference the Issue that you are resolving and then I'll merge the PR! Make sure you write `Closes #<Issue Number>` in the PR Description!
In case an Issue isn;t created, please create that and then send in the PR!
```
