### ISSUE TITLE
Scala - Add instructions to run Scala on Linux and MacOS

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#113]
Go to the folder for **Scala** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to edit the README for the same and make sure it covers all instructions on how to set up Scala Dev Environment on Linux and MacOS.
- [x] Linux
- [x] MacOS
 
If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by yohgenius** [comment]
Hello, i am a beginner in the open source world and interested to contribute for this code.
May i claim this issue? And where should i start?

**Comment by sbshah97** [comment]
Sure go ahead! No problems here!

**Comment by yohgenius** [comment]
okay, thanks... i will work on it right away

**Comment by Q-Mart** [comment]
Happy to claim if not done in 24 hours

**Comment by sbshah97** [comment]
Patience :stuck_out_tongue_closed_eyes: Other Issues are there as well :smile:
