### ISSUE TITLE
Add a code in Matlab for "Hello world"

### ISSUE THREAD

**Issue by Duxy1996** [salman-bhai/hello-world#160]
Go to the folder for **Matlab** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file. 

Your task is to create the `helloworld.mat` file and add code for the same there. If possible edit the README as well for more precise instructions on how to contribute to the repository.

If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by sbshah97** [comment]
Please make sure you reference this Issue when you submit your PR
