### ISSUE TITLE
Add fish (><>)

### ISSUE THREAD

**Issue by valkheim** [salman-bhai/hello-world#167]
Add a simple fish hello world

**Comment by EllenDeHopfen** [comment]
public class HelloWorld {
	public static void main(String[] args) {
		System.out.println("Hello World");
	}
}

**Comment by valkheim** [comment]
Is that Java ?
I was suggesting an hello world sample using fish esolang (not fish shell)
BTW, I can take it. I sometimes code with esoteric languages. I can add some

**Comment by hangnhat57** [comment]
"hello, world"r\
          o;!?l<
