### ISSUE TITLE
Update README to standard format

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#17]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager) to understand better.

**Comment by singh1114** [comment]
I'll do.

**Comment by sbshah97** [comment]
Go ahead! @singh1114
