### ISSUE TITLE
hello world in go

### ISSUE THREAD

**Issue by ksreenivasan** [salman-bhai/hello-world#20]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Add **Hello World** in golang.

**Comment by Flirre** [comment]
I'll do it!

**Comment by sbshah97** [comment]
Go ahead. Send a PR.

**Comment by Flirre** [comment]
I saw now that there is a hello world in Go commited just a couple of minutes ago, so I guess that's already done?

**Comment by sbshah97** [comment]
I guess so, I'm sorry man. People are pretty active these days.

**Comment by ksreenivasan** [comment]
@salman-bhai @Flirre : Sorry my bad. I intended on sending a separate pull request for it. But it got merged with the Readme change. 
(Serves me right for not branching)
