### ISSUE TITLE
Standardize format for title. 

### ISSUE THREAD

**Issue by Wferr** [salman-bhai/hello-world#22]
Almost every different example has a different variation on hello-world as the title. Should have a standard name. Im suggesting hello-world to stick with the name of the repo.

**Comment by akram-rameez** [comment]
Actually, I would love to see each language's file in a separate folder, with a Readme on how to install the compiler and run it.

This could get complicated, but its a start

**Comment by sbshah97** [comment]
That is a brilliant idea, @akram-rameez.

**Comment by sbshah97** [comment]
Hey, I'VE created another regarding both these ideas. I'll close this Issue for now.
