### ISSUE TITLE
Standard format for all the Hello World files

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#26]
Create a folder for each language where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(the file should be named hello-world.c or any other language that is there)** and a README file which tells you how to run the particular file in that language. 
The README should also contain steps to install that language on various OSs like Mac, Linux and Windows. If you don't know any of these steps, kindly create another Issue so that someone else can add the details. 

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

In the comments below kindly claim **only for one language**. After you're done with one language and have sent me a Pull Request regarding the same, you can move to another language.

Best of luck. Let the Hacktoberfest begin!!

**Comment by heath3n** [comment]
Claiming Python

**Comment by BondAnthony** [comment]
I'll take bash.

**Comment by ghost** [comment]
Claiming Javascript

**Comment by purnimamehta** [comment]
claiming HTML

**Comment by sbshah97** [comment]
Go ahead people.

**Comment by ivanovyordan** [comment]
claiming php

**Comment by ksreenivasan** [comment]
@salman-bhai : I didn't notice this before creating my PR. So leaving fortran here for someone else to claim.

**Comment by sumeshpremraj** [comment]
Claiming Ruby.

**Comment by sumeshpremraj** [comment]
Claiming C.

**Comment by sumeshpremraj** [comment]
Claiming Go.

**Comment by Ativerc** [comment]
Claiming C++

**Comment by sbshah97** [comment]
@kamikazekartik If you want you could go ahead and claim it. I doubt we'll have anyone claiming it!

**Comment by dumptyd** [comment]
Claiming C#

**Comment by dumptyd** [comment]
Claiming Java

**Comment by sbshah97** [comment]
Claiming Java! :smile:

**Comment by MartinMcGrath** [comment]
Claiming Perl

**Comment by suvojit-0x55aa** [comment]
Are esoteric languages allowed ??

**Comment by sbshah97** [comment]
Yes! @shin-migami

**Comment by suvojit-0x55aa** [comment]
@salman-bhai On it ! 👍

**Comment by Ativerc** [comment]
Claim Julia!

**Comment by dumptyd** [comment]
Claiming Lua

**Comment by sbshah97** [comment]
Go ahead!

**Comment by seancyw** [comment]
@salman-bhai Is C++ still open now? If yes, I would like to claim it :)

**Comment by Dinika** [comment]
Can I claim BASIC (since every other language I know has already been claimed)?

**Comment by dumptyd** [comment]
Claiming D.

**Comment by seancyw** [comment]
Claim for Erlang

**Comment by ShreyaSa** [comment]
Claim for R

**Comment by ShreyaSa** [comment]
claim for R

**Comment by cnorick** [comment]
Claiming B

**Comment by brandonbilbrey** [comment]
I would like to do Rust.

**Comment by sbshah97** [comment]
Keep going people. There are still a couple of languages up for grabs. Cherrs

**Comment by kbowen99** [comment]
Anyone Got TIBASIC? or F#? I'll Claim.

**Comment by pvdsp** [comment]
Claiming Racket

**Comment by sbshah97** [comment]
@kbowen99  Go ahead!

**Comment by brandonbilbrey** [comment]
Claiming Dart

**Comment by shrawnz** [comment]
Claiming Processing

**Comment by leonpw** [comment]
Claiming scala

**Comment by sbshah97** [comment]
People the remaining files have been moved as Separate Issues in the `Issues` tab. I'll close this Issue for now! Good work everyone and welcome to Open-Source!
Happy Hacktoberfest!
