### ISSUE TITLE
Create folder for 'Hello World' in Visual Basic and add README

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#66]
Create a folder for **Visual Basic** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(the file should be named hello-world.vb )** and a README file which tells you how to run the particular file in that language. 
The README should also contain steps to install that language on various OSs like Mac, Linux and Windows. If you don't know any of these steps, kindly create another Issue so that someone else can add the details. 

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by incomingstick** [comment]
I will add this one.
