### ISSUE TITLE
Create folder for 'Hello World' R Programming Language and create README

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#67]
Create a folder for **R** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(the file should be named hello-world.r )** and a README file which tells you how to run the particular file in that language. 
The README should also contain steps to install that language on various OSs like Mac, Linux and Windows. If you don't know any of these steps, kindly create another Issue so that someone else can add the details. 

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by anshuman73** [comment]
Hi, I'd like to work on this !

Just to confirm, I can already see a hello-world.r in the repo, I just to put it in a folder and add a readme according to the above specifications right ?

**Comment by sbshah97** [comment]
Yes, @anshuman73 you need to do exactly what you mentioned. Go ahead and work on it!
