### ISSUE TITLE
Add Instruction how to run Android and set it up

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/hello-world#99]
Go to the folder for **Android** where the name of the folder should be the name of the language itself. Inside the folder should be the `Hello World!` code of the file **(there will be quite a few files there)**.

Your task is to create a README for the same and make sure it covers all instructions on how to set up Android Dev Environment.

The README should also contain steps to install that language on various OSs like Mac, Linux and Windows. If you don't know any of these steps, kindly ping back in the comments so that I can help you out.

Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Best of luck. Let the Hacktoberfest begin!!

**Comment by sachincool** [comment]
I will work on this

**Comment by sbshah97** [comment]
@sachincool sure go ahead!

**Comment by sachincool** [comment]
should i send the pr  now ? or wait till 1st october   . as its my first hacktoberfest .

**Comment by priyankvex** [comment]
@sachincool Wait till October first if you want this to be counted in the Hacktoberfest :slightly_frowning_face:

**Comment by sachincool** [comment]
will i still have this issue assigned  till 1st october ? As it said you have to submit pr within 24 hours :cry:

**Comment by sbshah97** [comment]
Umm no! Issue reassigned every 24 hours! FCFS Applied here!

**Comment by sachincool** [comment]
@salman-bhai Oh ! thanks I'll wait  for the 1st oct then :+1:  you may  put the label "up for grabs" again .

**Comment by gupta-meghna64** [comment]
Hey!

**Comment by sachincool** [comment]
Claiming the issue :D

**Comment by sachincool** [comment]
Claiming the  Issue :1st_place_medal:

**Comment by sachincool** [comment]
please Look over it and feel free to point out any important details  which i may have missed :+1: @salman-bhai
